version: "3"

services:
  app:
    build: .
    image: selling-platform:mt
    container_name: selling-platform-mt
    entrypoint: /app/scripts/start.sh
    environment:
      PORT: 8181
      DB_HOST: db
      DB_PORT: ${DB_PORT:-5432}
      DB_PASS: ${DB_PASS:-postgres}
      DB_USER: ${DB_USER:-postgres}
      DB_NAME: ${DB_NAME:-selling-platform}
    ports:
      - "${PORT:-8181}:${PORT:-8181}"
    depends_on:
      - db

  db:
    image: postgres:9
    container_name: postgres-sp-mt
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_DB=${DB_NAME:-selling-platform}

volumes:
  db-data: